import express from "express";
import authRoutes from "../api/auth/Auth.route.js";
const router = express.Router();
import tenantRoutes from "../api/tenants/Tenant.route.js";
import roomRoutes from "../api/rooms/Room.route.js";
import auditLogRoutes from "./auditLog.routes.js";
import rentalRoutes from "../api/rental/rental.routes.js";
import agreementRoutes from "../api/agreements/Agreement.route.js";
import expenseRoutes from "../api/expenses/Expenses.route.js";
import maintenanceRoutes from "../api/maintenance/Maintenance.route.js";
import roomFeatureRoutes from "../api/roomFeature/roomFeature.routes.js";
import InvoiceRoutes from "../api/invoices/Invoice.route.js";
import paymentRoutes from "../api/payments/Payment.route.js";
// Auth routes
router.use("/auth", authRoutes);
router.use("/tenants", tenantRoutes);
router.use("/rooms", roomRoutes);
router.use("/audit", auditLogRoutes);
router.use("/rentals", rentalRoutes);
router.use("/agreements", agreementRoutes);
router.use("/expenses", expenseRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/roomfeature", roomFeatureRoutes);
router.use("/invoice", InvoiceRoutes);
router.use("/payments", paymentRoutes);
export default router;
